package cusError

import "fmt"

//独自のエラー処理のカスタマイズ

func Error2() {
	fmt.Println("エラーです。")
}
